-- MySQL Script generated by MySQL Workbench
-- 04/26/16 23:15:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema musichall1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musichall1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musichall1` DEFAULT CHARACTER SET utf8 ;
USE `musichall1` ;

-- -----------------------------------------------------
-- Table `musichall1`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall1`.`categorie` (
	`idCategorie` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall1`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall1`.`utilisateur` (
	`idUtilisateur` INT NOT NULL AUTO_INCREMENT,
	`nom` VARCHAR(45) NOT NULL,
	`prenom` VARCHAR(45) NOT NULL,
	`pseudo` VARCHAR(45) NOT NULL,
	`password` VARCHAR(45) NOT NULL,
	`email` VARCHAR(45) NOT NULL,
	`adresse` VARCHAR(400) NULL,
	`codepostal` VARCHAR(5) NULL,
	`ville` VARCHAR(255) NULL,
	`joinDate` DATE NOT NULL,
	`newsletter` TINYINT(4) NOT NULL,
	`codeSecu` INT NOT NULL,
	PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall1`.`souscategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall1`.`souscategorie` (
	`idSousCategorie` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	`idCategorie` INT NOT NULL,
	PRIMARY KEY (`idSousCategorie`),
	INDEX `fk_souscategorie_categorie1_idx` (`idCategorie` ASC),
	CONSTRAINT `fk_souscategorie_categorie1`
	FOREIGN KEY (`idCategorie`)
	REFERENCES `musichall1`.`categorie` (`idCategorie`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall1`.`materiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall1`.`materiel` (
	`idMateriel` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	`description` VARCHAR(255) NOT NULL,
	`prixAchHT` DOUBLE NOT NULL,
	`idSousCategorie` INT NOT NULL,
	`Marque` VARCHAR(45) NOT NULL,
	`Modele` VARCHAR(45) NOT NULL,
	`Fournisseur` VARCHAR(45) NOT NULL,
	`nbstock` INT NOT NULL,
	`cheminImage` VARCHAR(450) NULL,
	PRIMARY KEY (`idMateriel`),
	INDEX `fk_Materiel_SousCategorie1_idx` (`idSousCategorie` ASC),
	CONSTRAINT `fk_Materiel_SousCategorie1`
	FOREIGN KEY (`idSousCategorie`)
	REFERENCES `musichall1`.`souscategorie` (`idSousCategorie`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall1`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall1`.`commentaire` (
	`idCommentaire` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(255) NOT NULL,
	`idUtilisateur` INT NOT NULL,
	`idMateriel` INT NOT NULL,
	PRIMARY KEY (`idCommentaire`),
	INDEX `fk_Commentaire_Utilisateur1_idx` (`idUtilisateur` ASC),
	INDEX `fk_Commentaire_Materiel1_idx` (`idMateriel` ASC),
	CONSTRAINT `fk_Commentaire_Utilisateur1`
	FOREIGN KEY (`idUtilisateur`)
	REFERENCES `musichall1`.`utilisateur` (`idUtilisateur`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT `fk_Commentaire_Materiel1`
	FOREIGN KEY (`idMateriel`)
	REFERENCES `musichall1`.`materiel` (`idMateriel`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall1`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall1`.`commande` (
	`idCommande` INT NOT NULL AUTO_INCREMENT,
	`idUtilisateur` INT NOT NULL,
	`date` VARCHAR(45) NOT NULL,
	`status` VARCHAR(45) NOT NULL,
	`montant` INT NOT NULL,
	PRIMARY KEY (`idCommande`),
	INDEX `fk_Achat_utilisateur1_idx` (`idUtilisateur` ASC),
	CONSTRAINT `fk_Achat_utilisateur1`
	FOREIGN KEY (`idUtilisateur`)
	REFERENCES `musichall1`.`utilisateur` (`idUtilisateur`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musichall1`.`ligneCom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall1`.`ligneCom` (
	`idMateriel` INT NOT NULL,
	`idCommande` INT NOT NULL,
	`quantite` VARCHAR(45) NULL,
	INDEX `fk_ligneCom_materiel1_idx` (`idMateriel` ASC),
	CONSTRAINT `fk_ligneCom_materiel1`
	FOREIGN KEY (`idMateriel`)
	REFERENCES `musichall1`.`materiel` (`idMateriel`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT `fk_ligneCom_Commande1`
	FOREIGN KEY (`idCommande`)
	REFERENCES `musichall1`.`commande` (`idCommande`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
