-- MySQL Script generated by MySQL Workbench
-- 03/20/16 02:14:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema musichall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musichall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musichall` DEFAULT CHARACTER SET utf8 ;
USE `musichall` ;

-- -----------------------------------------------------
-- Table `musichall`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall`.`categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall`.`utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `joinDate` DATE NOT NULL,
  `newsletter` TINYINT(4) NOT NULL,
  `codeSecu` INT NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall`.`souscategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall`.`souscategorie` (
  `idSousCategorie` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  `idCategorie` INT NOT NULL,
  PRIMARY KEY (`idSousCategorie`),
  INDEX `fk_souscategorie_categorie1_idx` (`idCategorie` ASC),
  CONSTRAINT `fk_souscategorie_categorie1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `musichall`.`categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall`.`materiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall`.`materiel` (
  `idMateriel` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `prixAchHT` DOUBLE NOT NULL,
  `idSousCategorie` INT NOT NULL,
  `Marque` VARCHAR(45) NOT NULL,
  `Modele` VARCHAR(45) NOT NULL,
  `Fournisseur` VARCHAR(45) NOT NULL,
  `cheminImage` VARCHAR(450) NULL,
  PRIMARY KEY (`idMateriel`),
  INDEX `fk_Materiel_SousCategorie1_idx` (`idSousCategorie` ASC),
  CONSTRAINT `fk_Materiel_SousCategorie1`
    FOREIGN KEY (`idSousCategorie`)
    REFERENCES `musichall`.`souscategorie` (`idSousCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall`.`commentaire` (
  `idCommentaire` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  `idUtilisateur` INT NOT NULL,
  `idMateriel` INT NOT NULL,
  PRIMARY KEY (`idCommentaire`),
  INDEX `fk_Commentaire_Utilisateur1_idx` (`idUtilisateur` ASC),
  INDEX `fk_Commentaire_Materiel1_idx` (`idMateriel` ASC),
  CONSTRAINT `fk_Commentaire_Utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `musichall`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_Materiel1`
    FOREIGN KEY (`idMateriel`)
    REFERENCES `musichall`.`materiel` (`idMateriel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `musichall`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall`.`commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `idUtilisateur` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `montant` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
  INDEX `fk_Achat_utilisateur1_idx` (`idUtilisateur` ASC),
  CONSTRAINT `fk_Achat_utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `musichall`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musichall`.`ligneCom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musichall`.`ligneCom` (
  `idMateriel` INT NOT NULL,
  `idCommande` INT NOT NULL,
  `quantite` VARCHAR(45) NULL,
  INDEX `fk_ligneCom_materiel1_idx` (`idMateriel` ASC),
  CONSTRAINT `fk_ligneCom_materiel1`
    FOREIGN KEY (`idMateriel`)
    REFERENCES `musichall`.`materiel` (`idMateriel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligneCom_Commande1`
    FOREIGN KEY (`idCommande`)
    REFERENCES `musichall`.`commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
