-- MySQL Script generated by MySQL Workbench
-- 09/29/15 17:21:33
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 2014-musichall_musichall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2014-musichall_musichall` DEFAULT CHARACTER SET utf8 ;
USE `2014-musichall_musichall` ;

-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`categorie` (
	`idCategorie` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`utilisateur` (
	`idUtilisateur` INT NOT NULL AUTO_INCREMENT,
	`nom` VARCHAR(45) NOT NULL,
	`prenom` VARCHAR(45) NOT NULL,
	`pseudo` VARCHAR(45) NOT NULL,
	`password` VARCHAR(45) NOT NULL,
	`email` VARCHAR(45) NOT NULL,
	`joinDate` DATE NOT NULL,
	`newsletter` TINYINT(4) NOT NULL,
	`codeSecu` INT NOT NULL,
	PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`souscategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`souscategorie` (
	`idSousCategorie` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	`idCategorie` INT NOT NULL,
	PRIMARY KEY (`idSousCategorie`),
	INDEX `fk_souscategorie_categorie1_idx` (`idCategorie` ASC),
	CONSTRAINT `fk_souscategorie_categorie1`
	FOREIGN KEY (`idCategorie`)
	REFERENCES `2014-musichall_musichall`.`categorie` (`idCategorie`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`modele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`modele` (
	`idModele` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`idModele`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`fournisseur` (
	`idFournisseur` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`idFournisseur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`marque` (
	`idMarque` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`idMarque`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`materiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`materiel` (
	`idMateriel` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	`description` VARCHAR(45) NOT NULL,
	`prixAchHT` INT NOT NULL,
	`prixLoca` INT NOT NULL,
	`idSousCategorie` INT NOT NULL,
	`idMarque` INT NOT NULL,
	`idModele` INT NOT NULL,
	`idFournisseur` INT NOT NULL,
	PRIMARY KEY (`idMateriel`),
	INDEX `fk_Materiel_SousCategorie1_idx` (`idSousCategorie` ASC),
	INDEX `fk_materiel_modele1_idx` (`idModele` ASC),
	INDEX `fk_materiel_fournisseur1_idx` (`idFournisseur` ASC),
	INDEX `fk_materiel_marque1_idx` (`idMarque` ASC),
	CONSTRAINT `fk_Materiel_SousCategorie1`
	FOREIGN KEY (`idSousCategorie`)
	REFERENCES `2014-musichall_musichall`.`souscategorie` (`idSousCategorie`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT `fk_materiel_modele1`
	FOREIGN KEY (`idModele`)
	REFERENCES `2014-musichall_musichall`.`modele` (`idModele`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT `fk_materiel_fournisseur1`
	FOREIGN KEY (`idFournisseur`)
	REFERENCES `2014-musichall_musichall`.`fournisseur` (`idFournisseur`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT `fk_materiel_marque1`
	FOREIGN KEY (`idMarque`)
	REFERENCES `2014-musichall_musichall`.`marque` (`idMarque`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`commentaire` (
	`idCommentaire` INT NOT NULL AUTO_INCREMENT,
	`libelle` VARCHAR(45) NOT NULL,
	`idUtilisateur` INT NOT NULL,
	`idMateriel` INT NOT NULL,
	PRIMARY KEY (`idCommentaire`),
	INDEX `fk_Commentaire_Utilisateur1_idx` (`idUtilisateur` ASC),
	INDEX `fk_Commentaire_Materiel1_idx` (`idMateriel` ASC),
	CONSTRAINT `fk_Commentaire_Utilisateur1`
	FOREIGN KEY (`idUtilisateur`)
	REFERENCES `2014-musichall_musichall`.`utilisateur` (`idUtilisateur`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT `fk_Commentaire_Materiel1`
	FOREIGN KEY (`idMateriel`)
	REFERENCES `2014-musichall_musichall`.`materiel` (`idMateriel`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`Location` (
	`idLocation` INT NOT NULL,
	`idMateriel` INT NOT NULL,
	`idUtilisateur` INT NOT NULL,
	`dateDebut` DATE NOT NULL,
	`dateFin` DATE NOT NULL,
	PRIMARY KEY (`idLocation`),
	INDEX `fk_Location_utilisateur1_idx` (`idUtilisateur` ASC),
	CONSTRAINT `fk_Location_utilisateur1`
	FOREIGN KEY (`idUtilisateur`)
	REFERENCES `2014-musichall_musichall`.`utilisateur` (`idUtilisateur`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`Commande` (
	`idCommande` INT NOT NULL,
	`idUtilisateur` INT NOT NULL,
	`idMateriel` INT NOT NULL,
	`date` VARCHAR(45) NOT NULL,
	`status` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`idCommande`),
	INDEX `fk_Achat_utilisateur1_idx` (`idUtilisateur` ASC),
	CONSTRAINT `fk_Achat_utilisateur1`
	FOREIGN KEY (`idUtilisateur`)
	REFERENCES `2014-musichall_musichall`.`utilisateur` (`idUtilisateur`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`ligneCom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`ligneCom` (
	`idCommande` INT NOT NULL,
	`idMateriel` INT NOT NULL,
	`quantite` VARCHAR(45) NULL,
	PRIMARY KEY (`idCommande`),
	INDEX `fk_ligneCom_materiel1_idx` (`idMateriel` ASC),
	CONSTRAINT `fk_ligneCom_materiel1`
	FOREIGN KEY (`idMateriel`)
	REFERENCES `2014-musichall_musichall`.`materiel` (`idMateriel`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT `fk_ligneCom_Commande1`
	FOREIGN KEY (`idCommande`)
	REFERENCES `2014-musichall_musichall`.`Commande` (`idCommande`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2014-musichall_musichall`.`ligneLoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014-musichall_musichall`.`ligneLoc` (
	`idLocation` INT NOT NULL,
	`idMateriel` INT NOT NULL,
	`quantite` INT NOT NULL,
	PRIMARY KEY (`idLocation`),
	INDEX `fk_ligneLoc_materiel1_idx` (`idMateriel` ASC),
	CONSTRAINT `fk_ligneLoc_materiel1`
	FOREIGN KEY (`idMateriel`)
	REFERENCES `2014-musichall_musichall`.`materiel` (`idMateriel`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT `fk_ligneLoc_Location1`
	FOREIGN KEY (`idLocation`)
	REFERENCES `2014-musichall_musichall`.`Location` (`idLocation`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
